version: "3.9"

services:
  goof:
    build: .
    container_name: goof-new
    environment:
      - DOCKER=1
      - MONGO_URI=mongodb://goof-mongo-new:27018/acme
      - MYSQL_HOST=goof-mysql-new
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=acme
    ports:
      - "3001:3001"
      - "9229:9229"
    depends_on:
      - goof-mongo
      - goof-mysql
    networks:
      - goof-network

  goof-mongo:
    image: mongo:3
    container_name: goof-mongo-new
    ports:
      - "27018:27017"   # host:container
    networks:
      - goof-network
    volumes:
      - mongo-data:/data/db

  goof-mysql:
    image: mysql:5
    container_name: goof-mysql-new
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acme
    ports:
      - "3307:3306"     # host:container
    networks:
      - goof-network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mongo-data:
  mysql-data:

networks:
  goof-network:
    driver: bridge
